[2025-05-25T12:37:53.465+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-25T12:37:53.494+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_operator.venv_b scheduled__2025-05-24T00:00:00+00:00 [queued]>
[2025-05-25T12:37:53.506+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_operator.venv_b scheduled__2025-05-24T00:00:00+00:00 [queued]>
[2025-05-25T12:37:53.507+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-25T12:37:53.520+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonVirtualenvOperator): venv_b> on 2025-05-24 00:00:00+00:00
[2025-05-25T12:37:53.527+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=272) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T12:37:53.529+0000] {standard_task_runner.py:63} INFO - Started process 275 to run task
[2025-05-25T12:37:53.529+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_branch_operator', 'venv_b', 'scheduled__2025-05-24T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator.py', '--cfg-path', '/tmp/tmpd17fl76p']
[2025-05-25T12:37:53.531+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask venv_b
[2025-05-25T12:37:53.579+0000] {task_command.py:426} INFO - Running <TaskInstance: example_branch_operator.venv_b scheduled__2025-05-24T00:00:00+00:00 [running]> on host af29f3c8a508
[2025-05-25T12:37:53.658+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_operator' AIRFLOW_CTX_TASK_ID='venv_b' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-24T00:00:00+00:00'
[2025-05-25T12:37:53.659+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-25T12:37:53.660+0000] {baseoperator.py:400} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-05-25T12:37:53.668+0000] {python.py:708} INFO - Python virtual environment will be cached in /tmp/venv-5ea997a7
[2025-05-25T12:37:53.669+0000] {python.py:720} INFO - Re-using cached Python virtual environment in /tmp/venv-5ea997a7
[2025-05-25T12:37:53.676+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venv-5ea997a7/bin/python /tmp/venv-callje4zb9s0/script.py /tmp/venv-callje4zb9s0/script.in /tmp/venv-callje4zb9s0/script.out /tmp/venv-callje4zb9s0/string_args.txt /tmp/venv-callje4zb9s0/termination.log
[2025-05-25T12:37:53.677+0000] {process_utils.py:187} INFO - Output:
[2025-05-25T12:37:55.928+0000] {process_utils.py:191} INFO - Hello World with some numpy stuff: [0 1 2 3 4 5]
[2025-05-25T12:37:56.240+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-25T12:37:56.241+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-25T12:37:56.251+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=example_branch_operator, task_id=venv_b, run_id=scheduled__2025-05-24T00:00:00+00:00, execution_date=20250524T000000, start_date=20250525T123753, end_date=20250525T123756
[2025-05-25T12:37:56.313+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-25T12:37:56.334+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-25T12:37:56.336+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
